-- MySQL Script generated by MySQL Workbench
-- 02/03/16 22:38:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sys_co_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sys_co_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `sys_co_db` ;

-- -----------------------------------------------------
-- Table `sys_co_db`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`empleado` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`empleado` (
  `id_empleado` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `materno` VARCHAR(50) NULL,
  `paterno` VARCHAR(50) NULL,
  `sexo` CHAR NULL,
  `id_turno` INT NULL,
  `id_departamento` INT NULL,
  `id_estado` CHAR NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`departamento` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`departamento` (
  `id_departamento` INT NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `id_area` INT NULL,
  `estado` CHAR NULL,
  PRIMARY KEY (`id_departamento`),
  UNIQUE INDEX `id_departamento_UNIQUE` (`id_departamento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`area` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`area` (
  `id_area` INT NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `estado` CHAR NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`presentacion_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`presentacion_medicamento` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`presentacion_medicamento` (
  `id_presentacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  `cantidad` INT NULL,
  `estado` CHAR NULL,
  PRIMARY KEY (`id_presentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`medicamento` (
  `id_medicamento` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NULL,
  `descripcion` VARCHAR(150) NULL,
  `precio` DECIMAL(10) NULL,
  `id_presentacion_entrada` INT NULL,
  `id_presentacion_salida` INT NULL,
  `fecha_alta` DATETIME NULL,
  `fecha_baja` DATETIME NULL,
  `estado` CHAR NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `rol` CHAR NULL,
  `estado` CHAR NULL,
  `fecha_alta` DATETIME NULL,
  `id_usuario_creacion` INT NULL,
  `fecha_baja` DATETIME NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`consulta` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`consulta` (
  `id_consulta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `id_empleado` INT NULL,
  `peso` DECIMAL(10) NULL,
  `talla` DECIMAL(10) NULL,
  `altura` DECIMAL(10) NULL,
  `frecuenca_respiratoria` INT NULL,
  `frecuencia_cardiaca` INT NULL,
  PRIMARY KEY (`id_consulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_co_db`.`relacion_consulta_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_co_db`.`relacion_consulta_medicamento` ;

CREATE TABLE IF NOT EXISTS `sys_co_db`.`relacion_consulta_medicamento` (
  `id_consulta` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_consulta`, `id_medicamento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
